### ISSUE TITLE
DATA line remains in output state

### ISSUE THREAD

**Issue by vladkorotnev** [vladkorotnev/SMPEmu#13]
As reported by @piotr433:

> Everything works as expected, but sometimes after reboot the keyboard stops responding on the initial screen, where you have to choose between BASIC/SMP0/SMP1. Pressing a key only emits a beep. Reset of the ATMEGA8 unblocks the keyboard. I noticed that the ATMEGA8 board sometimes leaves the DATA line in an output state. I suspected that the do_send_byte procedure may be a bit too slow, and indeed, some trivial optimizations fixed the problem. Perhaps it wouldn't occur with a 20MHz crystal. Attached is a modified SMPEmu.ino file. List of changes:
> 1. the "for" loop control variable "i" doesn't need to be of 16-bit "int" type
> 2. comparing with 0 is likely faster than with 8, because decrementing a register already sets the Z flag
> 3. ++i is likely faster than i++, because in the later case the previous value of "i" needs to be stored somewhere

**Comment by vladkorotnev** [comment]
@BOOtak @piotr433 Please test with the new commit on prototype branch, which switches back to data input after sending each byte

**Comment by piotr433** [comment]
The issue can be conveniently tested by replacing all occurrences of DDRD = B11000111 with DDRD = B11000110 and connecting a LED through a ~2.2 kohm resistor to the pin PD0. The state of the LED would then reflect the state of the DATA line direction. If the DATA pin is configured as input, the LED is faintly lit too through an ATMEGA internal pull-up resistor.
In my tests the DATA line is erroneously switched to output at the moment of confirming the file name with the key [ВК], before displaying the message "Перезагружаюсь!". My modifications described earlier in this thread actually **didn't fix** the issue, it still persists.
My ATMEGA8 board doesn't use the recommended 270 ohm resistor in series with the DATA line. Perhaps with this resistor the calculator wouldn't be blocked.
Also the SMP port can only supply a limited current, according to **spark-sys** tests up to ca. 15mA. In case of bus conflicts the current consumption would increase. My ATMEGA8 board wasn't powered from the calculator, but from an external power supply.
I will be back with more test results later.

**Comment by vladkorotnev** [comment]
>  My modifications described earlier in this thread actually didn't fix the issue, it still persists.
Yep, however 93ef121 should fix it.

> ...up to ca. 15mA. In case of bus conflicts the current consumption would increase.
Hopefully 15mA is enough for an atmega + micro SD card. As for the bus conflicts, this is why it's advised to connect the IO lines through small resistors, to avoid current bursts in such cases.

**Comment by piotr433** [comment]
More test results and thoughts:

Adding the series resistors to my ATMEGA8 board nor the latest update 93ef121 didn't help.

The do_send_byte procedure is used by the commands 0x00, 0x10, 0xB0, 0xD0, 0xF0. I have added more LEDs to the board to identify the culprit. I found out that the program gets stuck in the command 0x00, in the do_send_byte procedure. Removing the command 0x00 seems to cure the problem, even in the 6dbcd84 version.

What I don't understand:

1. How did the program get there in the first place?

2. Why cannot it leave the do_send_byte procedure? Perhaps the CLOCK pulses disappear in a bus conflict? Unfortunately, I don't have an oscilloscope at home. I will try to look at the bus signals tomorrow at work.

The problem occurs when the key [ВК] is pressed. In this moment the calculator sends the command 0xF1 to the SMP bus with the procedure EMUSEL. Perhaps it messes something? I will try to comment it out and see what happens.

My own crude SMP emulator didn't support the command 0x00. Adding it didn't change anything.

**Comment by vladkorotnev** [comment]
Probably when the calculator queries the lock status with  0x00, it might just read one bit and deselect the cartridge, ignoring the rest?

And the send routine doesn't have a condition to exit when the SELECT signal is lost, thus getting stuck.

What is the problem with 0xF1 though? There is essentially no code currently handling that command, at least on the prototype branch, so it should be pretty much ignored.
The EMUSEL routine should just throw an ASCII string at the cartridge containing the file name to mount.

I have a logic analyzer, but don't yet have a calculator to test on, at least for the time being. 

If you want, I suggest you look up "Saleae" logic analyzer clones on Aliexpress, they are very cheap (like $5 free shipping), have software for Windows/Linux/Mac, and can work up to 24 MHz. The original Saleae also has analog inputs and all kinds of safety stuff, but it's nearly 50 times more expensive :(

**Comment by piotr433** [comment]
I think that I hit the nail with the command 0xF1. It is followed by data bytes which aren't processed in the "case 0xF1:" of the ATMEGA program. The 0xF1 routine should at least wait for the rising slope of the SELECT signal, otherwise the incoming data bytes will be interpreted as command codes.

**Comment by piotr433** [comment]
Waiting for SELECT=1 in the 0xF1 routine indeed helps. @vladkorotnev, I leave the SMPEmu.ino modification to you. I will test the updated version ASAP.

**Comment by vladkorotnev** [comment]
@piotr433 Added in def546a :-)

**Comment by piotr433** [comment]
It's OK now. I'm closing the case!
