### ISSUE TITLE
More hardware vs. emulated bugs

### ISSUE THREAD

**Issue by vladkorotnev** [vladkorotnev/SMPEmu#5]
The keyboard works on the emulator, but not on the real MK90, also appears that the file list won't display too (the test shot doesn't have "TODO" on display)

**Comment by vladkorotnev** [comment]
File list → #7

**Comment by vladkorotnev** [comment]
According to http://piotr433.archives.genjit.su/mk90hwe.htm:

`Pressing a key also causes an interrupt request to the vector at address $00C8.`
...
`$E814 - control and status register, byte size`
...
`cleared bit 4 enables external interrupts (i.e. CLK signal in the slave mode) to the vector $00C8, lowest priority`


Todo: check if bit 4 is set/re-set according to the code, and whether it has any effect on the keyboard prompt working or not.

**Comment by vladkorotnev** [comment]
@BOOtak please test and confirm, trying various options at:

https://github.com/vladkorotnev/SMPEmu/blob/955f048e452fd348d3a555a8c84ae5adc9b91f0b/pdp/pdpfw.mac#L108

**Comment by vladkorotnev** [comment]
Actually considering that `GETCH = B250h`, which in turn has `mov #342,@#SMPCS`, this line above is pointless and may cause many kinds of bugs. However we need to configure the serial port properly before contacting the KBCU, which would be

```
mov #1000, @#SMPBAUD
```

and then a call to GETCH, I suppose?

**Comment by vladkorotnev** [comment]
Reported as working fine by @BOOtak 

Another mystery solved

**Comment by vladkorotnev** [comment]
As reported by Piotr Piatek:

> Hello,
> 
> Since a few days I'm a proud owner of a real MK-90. I tried your SMPEmu program on it and I'm sorry to inform you that the keyboard still doesn't work. Setting the baud rate is likely meaningless. The real cause appears to be a missing closing sequence in the subroutines EMULS and EMUSEL. Following two lines need to be inserted just before the instruction "rts pc":
> tst @#SMPCMD
> jsr pc,(r2)
> 
> Apparently, the keyboard communication channel 2 cannot be opened until the SMP channel 0 is closed.

Why did it work on @BOOtak 's device though?

![n0kfdm8phq0](https://user-images.githubusercontent.com/656194/38853853-ffb4fc7c-4237-11e8-988e-0f8c8a955596.jpg)

More investigation needed, it seems!

**Comment by vladkorotnev** [comment]
As explained by Piotr:

> I saw the photo and I'm puzzled...
> 
> Reading the register SMPCMD deasserts the signal SELECT (END in the original documentation) and terminates the serial transfer.
> 
> Perhaps writing to the SMPBAUD has the same effect, but not on every machine. There exist at least two hardware versions of the MK-90 - the older one with ceramic chips and the RTC in a 48-pin package, and the later one with plastic chips and the RTC in a 32-pin package (mine is of this kind).

Will now try adding the suggested code into the prototype branch.

**Comment by piotr433** [comment]
Hello Vladislav,

Sorry for the long delay.

I wanted to ask other MK-90 users to test both versions and share the results, but the file "smp0.bin" in the prototype branch crashes the calculator. There's not enough space for the instruction "jmp cont" before the interrupt vector, the code needs to be split one instruction earlier. Could you fix it, please?

Also, I repeated the test of the master branch version and, surprisingly, the keyboard sometimes works, once in 5 restarts or so.

**Comment by spark-sys** [comment]
Hello.

**piotr433** asked me to test both (master and prototype) versions of the PDP side firmware on real MK-90.
I tested on two MK-90 available to me (production dates are May 1989 and Jun 1989).
Master branch version  locks the keyboard. Prototype branch version looks fine. At least the keyboard works after automatic restart :)

**Comment by vladkorotnev** [comment]
@spark-sys

Hello and thanks for your help! Are you certain that you tested the latest PDP version (today's commit)? As I said above, I only rebuilt the bin file, but the h-file needed to be updated via bin2c. 

If you did update it please consider making a pull request as I won't be at my computer until end of week. 

Thanks!

**Comment by vladkorotnev** [comment]
@piotr433 Thanks for updating `pdp.h`
@spark-sys If you tested the .bin file, then yes, it is the latest (I suppose you tested it with original SMP module rather than the GenjitsuSMP arduino-based hardware)

I guess another mystery busted for now?

Many thanks for your help guys!

**Comment by spark-sys** [comment]
@vladkorotnev Yes, I tested the .bin with original SMP.
