### ISSUE TITLE
Please remove duplicate EMULS call in SMPEmu code.

### ISSUE THREAD

**Issue by BOOtak** [vladkorotnev/SMPEmu#7]
Calling two subsequent EMULS calls on MK 90 side causing Arduino to process two subsequent List files commands incorrectly.

**Comment by BOOtak** [comment]
https://github.com/vladkorotnev/SMPEmu/blob/754b309045d567896b7ae535d0b4150464406070/pdp/pdpfw.mac#L157-L159

**Comment by vladkorotnev** [comment]
Xref #5 
Branch → https://github.com/vladkorotnev/mk90emsr/issues/1
